
import java.awt.Component;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Alejandra Barrera Mesa, Diego Pérez Reyes, Fernanda Loaeza Viadas, Santiago Payro Costilla
 * @version 2.6
 * 
 * <pre>
 * 
 *  Clase GUICalculadora
 *  
 *  Interfaz grafica capaz de operar los numeros dados.
 *  Contiene los botones fundamentales de una calculadora.
 * </pre>
 */
public class GUICalculadora extends javax.swing.JFrame {
    private String formula;
    protected double resultado;
    private boolean bandpunto;
    private boolean bandop;
            
    /**
     * Creates new form GUICalculadora
     */
    public GUICalculadora() {
        initComponents();
        this.formula="";
        this.bandpunto=false;
        this.bandop=false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextFieldRes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaFormula = new javax.swing.JTextArea();
        ButtonEntre = new javax.swing.JButton();
        ButtonPor = new javax.swing.JButton();
        ButtonMenos = new javax.swing.JButton();
        ButtonMas = new javax.swing.JButton();
        ButtonIgual = new javax.swing.JButton();
        ButtonPotencia = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonPunto = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonMasMenos = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        ButtonBorrar = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonANS = new javax.swing.JButton();
        ButtonParC = new javax.swing.JButton();
        ButtonParA = new javax.swing.JButton();
        ButtonCE = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextFieldRes.setEditable(false);
        TextFieldRes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TextFieldRes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextFieldRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldResActionPerformed(evt);
            }
        });

        TextAreaFormula.setEditable(false);
        TextAreaFormula.setColumns(20);
        TextAreaFormula.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TextAreaFormula.setRows(5);
        jScrollPane1.setViewportView(TextAreaFormula);

        ButtonEntre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonEntre.setText("÷");
        ButtonEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntreActionPerformed(evt);
            }
        });

        ButtonPor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonPor.setText("X");
        ButtonPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPorActionPerformed(evt);
            }
        });

        ButtonMenos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonMenos.setText("-");
        ButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenosActionPerformed(evt);
            }
        });

        ButtonMas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonMas.setText("+");
        ButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMasActionPerformed(evt);
            }
        });

        ButtonIgual.setBackground(new java.awt.Color(153, 153, 153));
        ButtonIgual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonIgual.setText("=");
        ButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualActionPerformed(evt);
            }
        });

        ButtonPotencia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonPotencia.setText("xⁿ");
        ButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPotenciaActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        ButtonPunto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonPunto.setText(".");
        ButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPuntoActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonMasMenos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonMasMenos.setText("±");
        ButtonMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMasMenosActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        ButtonBorrar.setBackground(new java.awt.Color(153, 153, 153));
        ButtonBorrar.setText("Borrar");
        ButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        ButtonC.setBackground(new java.awt.Color(153, 153, 153));
        ButtonC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonANS.setBackground(new java.awt.Color(153, 153, 153));
        ButtonANS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonANS.setText("ANS");
        ButtonANS.setActionCommand("");
        ButtonANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonANSActionPerformed(evt);
            }
        });

        ButtonParC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonParC.setText(")");
        ButtonParC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonParCActionPerformed(evt);
            }
        });

        ButtonParA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonParA.setText("(");
        ButtonParA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonParAActionPerformed(evt);
            }
        });

        ButtonCE.setBackground(new java.awt.Color(153, 153, 153));
        ButtonCE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ButtonCE.setText("CE");
        ButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldRes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonParC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonANS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonParA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldRes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonANS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonParA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonParC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonMasMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo que agrega accion a la pantalla de resultados
     * @deprecated No es necesario hacer acciones en la pantalla de resultados
    **/
    private void TextFieldResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldResActionPerformed
    
    /**
     * Borra el ultimo caracter de la formula
     */
    private void ButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarActionPerformed
        if(formula.length()>1)
            formula=formula.substring(0, formula.length()-1);
        TextAreaFormula.setText(formula);
    }//GEN-LAST:event_ButtonBorrarActionPerformed

    /**
     * Clear: Borra la formula, y vacia las pantallas formula y resultado
     */
    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        formula="";
        TextAreaFormula.setText(formula);
        TextFieldRes.setText("");
    }//GEN-LAST:event_ButtonCActionPerformed
    
    /**
     * Boton potencia
     */
    private void ButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPotenciaActionPerformed
        if(!bandop){
            TextAreaFormula.append("^");
            formula+="^";
            this.bandpunto=!bandpunto;
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonPotenciaActionPerformed

    /**
     * Boton division
     */
    private void ButtonEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntreActionPerformed
        if(!bandop){
            TextAreaFormula.append("÷");
            formula+="/";
            this.bandpunto=!bandpunto;
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonEntreActionPerformed

    /**
     * Boton suma
     */
    private void ButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMasActionPerformed
        if(!bandop){
            TextAreaFormula.append("+");
            formula+="+";
            this.bandpunto=!bandpunto;
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonMasActionPerformed

    /**
     * Boton negativo
     */
    private void ButtonMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMasMenosActionPerformed
        String op="-+*/^";
        
        if(formula.isEmpty() || formula.charAt(formula.length()-1)!='-'){
            TextAreaFormula.append("-");
            formula+="-";
            this.bandpunto=!bandpunto;
        }else if(!formula.isEmpty() && !op.contains(formula.charAt(formula.length()-1)+"")){
            formula='-'+formula;
            TextAreaFormula.setText(formula);
        }else{
            formula=formula.substring(0, formula.length()-1);
            TextAreaFormula.setText(formula);
        }
    }//GEN-LAST:event_ButtonMasMenosActionPerformed

    /**
     * Boton resta
     */
    private void ButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenosActionPerformed
        if(!bandop){
            TextAreaFormula.append("-");
            formula+="-";
            this.bandpunto=!bandpunto;
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonMenosActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        TextAreaFormula.append("1");
        formula+="1";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button1ActionPerformed

     /**
     * Boton multiplicacion
     */
    private void ButtonPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPorActionPerformed
        if(!bandop){
            TextAreaFormula.append("*");
            formula+="*";
            this.bandpunto=!bandpunto;
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonPorActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        TextAreaFormula.append("4");
        formula+="4";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button4ActionPerformed

     /**
     * Boton punto
     */
    private void ButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPuntoActionPerformed
        if(!bandpunto){
            TextAreaFormula.append(".");
            formula+=".";
            this.bandpunto=!bandpunto;
        }
    }//GEN-LAST:event_ButtonPuntoActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        TextAreaFormula.append("7");
        formula+="7";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        TextAreaFormula.append("3");
        formula+="3";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        TextAreaFormula.append("6");
        formula+="6";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        TextAreaFormula.append("9");
        formula+="9";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        TextAreaFormula.append("0");
        formula+="0";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        TextAreaFormula.append("2");
        formula+="2";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        TextAreaFormula.append("5");
        formula+="5";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        TextAreaFormula.append("8");
        formula+="8";
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_Button8ActionPerformed

     /**
     * Boton igual
     */
    private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualActionPerformed
        String posfija;
        String op="+-*/^";
        
        if(formula.isEmpty()){
            formula=TextAreaFormula.getText();
        }

            if(Calculadora.validaParentesis(formula)){
                posfija=Calculadora.posFija(formula);
                if(Calculadora.validaPosfija(posfija)){
                    resultado=Calculadora.operaPosfija(posfija);
                    TextFieldRes.setText(resultado+"");
                }else if(!op.contains(formula.charAt(formula.length()-1)+"")){
                    TextFieldRes.setText(formula);
                }else
                    TextFieldRes.setText("SYNTAX ERROR");
            }else{
                TextFieldRes.setText("SYNTAX ERROR");
            }
        
        this.bandpunto=!bandpunto;
    }//GEN-LAST:event_ButtonIgualActionPerformed

     /**
     * Boton Answer
     */
    private void ButtonANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonANSActionPerformed
        TextAreaFormula.append("ANS");
        formula+=resultado;
        if(bandop){
            bandop=!bandop;
        }
    }//GEN-LAST:event_ButtonANSActionPerformed

    private void ButtonParCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonParCActionPerformed
        TextAreaFormula.append(")");
        formula+=")";
    }//GEN-LAST:event_ButtonParCActionPerformed

    private void ButtonParAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonParAActionPerformed
        TextAreaFormula.append("(");
        formula+="(";
    }//GEN-LAST:event_ButtonParAActionPerformed

     /**
     * Clear Expresion: Borra la formula y vacia la pantalla Formula
     */
    private void ButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCEActionPerformed
        formula="";
        TextAreaFormula.setText(formula);
    }//GEN-LAST:event_ButtonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonANS;
    private javax.swing.JButton ButtonBorrar;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonCE;
    private javax.swing.JButton ButtonEntre;
    private javax.swing.JButton ButtonIgual;
    private javax.swing.JButton ButtonMas;
    private javax.swing.JButton ButtonMasMenos;
    private javax.swing.JButton ButtonMenos;
    private javax.swing.JButton ButtonParA;
    private javax.swing.JButton ButtonParC;
    private javax.swing.JButton ButtonPor;
    private javax.swing.JButton ButtonPotencia;
    private javax.swing.JButton ButtonPunto;
    private javax.swing.JTextArea TextAreaFormula;
    private javax.swing.JTextField TextFieldRes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
